### ISSUE TITLE
Media queries

### ISSUE THREAD

**Issue by wooorm** [Cascuna/cssttr#10]
Have you checked if your grid works nice on smaller displays?

https://github.com/Cascuna/cssttr/blob/19db203ce78f444dac42f0a810cb675cb0c2a1af/styles.css#L29

Tip: start with mobile design, and then if a screen is wide enough, apply the grid!

**Comment by Cascuna** [comment]
Seemed to look fine when I was testing, as only the middle column would show in small screen resolutions. I'll give it some more thought & will implement media queries to have more control of the situation.
