### ISSUE TITLE
Unknown `<content>` element!

### ISSUE THREAD

**Issue by wooorm** [Cascuna/cssttr#7]
https://github.com/Cascuna/cssttr/blob/19db203ce78f444dac42f0a810cb675cb0c2a1af/styleguide.html#L38

🤔

**Comment by Cascuna** [comment]
Good catch. Was meant to be `<main>`

**Comment by wooorm** [comment]
Oh, P.S., id’s are not allowed ;)

**Comment by wooorm** [comment]
right? I thought ids and classes were not allowed!

**Comment by Cascuna** [comment]
I asked vasilus if it was okay to use the ID to implement a "go-to" content button, and got his blessing for this

**Comment by wooorm** [comment]
Who’s Vasilus? 🤔

**Comment by wooorm** [comment]
https://twitter.com/vasilis? 😉

**Comment by Cascuna** [comment]
Smart ass 🤓 https://vasilis.nl/
Names are difficult!

**Comment by wooorm** [comment]
One of the hard things in programming 😉
