### ISSUE TITLE
CSS variables

### ISSUE THREAD

**Issue by wooorm** [Cascuna/cssttr#9]
I saw you started work on that!

https://github.com/Cascuna/cssttr/blob/19db203ce78f444dac42f0a810cb675cb0c2a1af/styles.css#L3

...but it’s commented out, how are you planning on implementing those?

**Comment by Cascuna** [comment]
My strategy is to use the CSS variables for my usage of colors and fonts as a starter. The commented out variable was merely used for testing and since it was used in one location only, I got rid of it.
